name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ mastername: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
